/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/tutorial/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/tutorial/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/tutorial/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/tutorial/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/tutorial/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/tutorial/icons/IconTooling.vue')['default']
    OldReactWelcome: typeof import('./src/components/tutorial/OldReactWelcome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/tutorial/TheWelcome.vue')['default']
    VueWelcome: typeof import('./src/components/tutorial/VueWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/tutorial/WelcomeItem.vue')['default']
  }
}
